image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

stages:
  - validate

validate:
  stage: validate
  script:
    - terraform validate
    - find . -type f -name '*.tf' -exec terraform fmt {} \;
  only:
    - branches
