output "eks1_cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks1.cluster_endpoint
}

output "eks1_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks1.cluster_security_group_id
}

output "eks1_kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks1.kubeconfig
}

output "eks1_config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks1.config_map_aws_auth
}

output "eks2_cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks2.cluster_endpoint
}

output "eks2_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks2.cluster_security_group_id
}

output "eks2_kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks2.kubeconfig
}

output "eks2_config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks2.config_map_aws_auth
}

output "region" {
  description = "AWS region."
  value       = var.region
}

