---
timeout: 3600s
logsBucket: "gs://${PROJECT_ID}/logs/cloudbuild"
substitutions:
  _SSH: "true"
  _HUB: "true"
tags:
  - project-setup
steps:
  - name: gcr.io/${PROJECT_ID}/platform-installer
    id: "prod-gcp-ssh-key"
    dir: infrastructure/prod/gcp/ssh_key
    entrypoint: "bash"
    args:
      - "-xe"
      - "-c"
      - |
        [[ "${_SSH}" == "false" ]] && exit 0
        terraform init
        terraform plan -out terraform.tfplan
        terraform apply -input=false -lock=false terraform.tfplan
  - name: gcr.io/${PROJECT_ID}/platform-installer
    id: "prod-gcp-hub-gsa"
    dir: infrastructure/prod/gcp/hub_gsa
    waitFor: ['-']
    entrypoint: "bash"
    args:
      - "-xe"
      - "-c"
      - |
        [[ "${_HUB}" == "false" ]] && exit 0
        terraform init
        terraform plan -out terraform.tfplan
        terraform apply -input=false -lock=false terraform.tfplan 
