apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../templates/virtualservice--in-gke-for-eks.yaml

commonAnnotations:
  configmanagement.gke.io/cluster-selector: gke-prod-us-west2a-1

commonLabels:
  provider: gcp
  cluster: gke-prod-us-west2a-1