apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: 
  policyController:
    enabled: true
    templateLibraryInstalled: true
  git:
    syncRepo: XYZ
    secretType: ssh
