kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend
spec:
  template:
    spec:
      serviceAccountName: frontend
      containers:
        - name: server
          env:
            - name: ENV_PLATFORM
              value: aws
