apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../templates/service-eks-redis.yaml

commonAnnotations:
  configmanagement.gke.io/cluster-selector: aws-prod-ha

commonLabels:
  provider: aws
