apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../templates/service-gke-redis.yaml

commonAnnotations:
  configmanagement.gke.io/cluster-selector: gcp-prod-ha

commonLabels:
  provider: gcp