apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../templates/serviceentry--eks-internal-dns.yaml
  - ../../../templates/serviceentry--in-eks-for-gke-global.yaml

commonAnnotations:
  configmanagement.gke.io/cluster-selector: eks-prod-us-west2ab-1

commonLabels:
  provider: aws
  cluster: eks-prod-us-west2ab-1