apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
- multiclusteringress-frontend-patch.yaml
- multiclusterservice-frontend-patch.yaml
resources:
- ../../templates/backendconfig-istio-ingressgateway.yaml
- ../../templates/multiclusteringress-frontend.yaml
- ../../templates/multiclusterservice-istio-ingressgateway.yaml
commonAnnotations:
  configmanagement.gke.io/cluster-selector: gke-dev-us-west1a-1
