apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../templates/gateway--frontend-gateway.yml
  - ../../../templates/virtualservice--frontend-ingress.yml
  - ../../../templates/virtualservice--frontend.yml
  - ../../../templates/destinationrule--frontend.yaml

patches:
  - gateway-frontend-patch.yaml
  - virtualservice-frontend-patch.yaml
