apiVersion: networking.gke.io/v1beta1
kind: MultiClusterIngress
metadata:
  name: obfrontend-istio-mci
  annotations:
    networking.gke.io/pre-shared-certs: "shop-managed-ssl-cert"
spec:
  template:
    spec:
      backend:
        serviceName: obfrontend-istio-mcs
        servicePort: 80
      rules:
      - host: OB_HOSTNAME
        http:
          paths:
          - backend:
              serviceName: obfrontend-istio-mcs
              servicePort: 80
