---
timeout: 3600s
logsBucket: "gs://${PROJECT_ID}/logs/cloudbuild"
tags:
  - bank-of-anthos-loadgenerator
steps:
  - name: gcr.io/${PROJECT_ID}/platform-installer
    id: "build-loadgenerator"
    entrypoint: "bash"
    args:
      - -c
      - gcloud builds submit . --tag=gcr.io/${PROJECT_ID}/bank-of-anthos/loadgenerator
