output "eks_list" {
  value = [
    "${module.eks-stage-1.cluster_id}"
  ]
}

output "eks1_cluster_id" {
  description = "eks1 cluster name"
  value       = module.eks-stage-1.cluster_id
}

output "eks1_cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks-stage-1.cluster_endpoint
}

output "eks1_cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks-stage-1.cluster_security_group_id
}

output "eks1_kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks-stage-1.kubeconfig
}

output "eks1_config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks-stage-1.config_map_aws_auth
}

