  values:
    kiali:
      createDemoSecret: true
    global:
      mtls:
        enabled: true
      multiCluster:
        clusterName: ${GKE}
      network: ${GCP_NET}
      meshNetworks:
        ${GCP_NET}:
          endpoints:
          # Always use Kubernetes as the registry name for the main cluster in the mesh network configuration
